name = "VendingSearch"; 								                                        // name 
picture = "";			                                        // picture in expanded description
logoSmall = "";	                                            // icon next to mod name when description is not expanded
logo = "";				                                    	// logo below game menu
logoOver = "";	                                            	// on mouse hover over logo
tooltip = "VendingSearch by Zedmag";						                    // tool tip on mouse hover
overview = "Adds the chance to find drinks at ANY vending machine"; 									// overview
action = "";						// link
author = "Zedmag";							                                    // author
version = "1.5"; 
